# Default Theme

if patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'0'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'7'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}


# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"tmux_session_info 10 15" \
		"hostname 4 15" \
		# "ifstat 30 255" \
		# "ifstat_sys 30 255" \
		"lan_ip 12 15 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
		"wan_ip 12 15" \
		"vcs_branch 4 15" \
		"vcs_compare 5 15" \
		"vcs_staged 2 15" \
		"vcs_modified 9 15" \
		"vcs_others 12 0" \
	)
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		#"earthquake 3 0" \
		"mailcount 1 15" \
		# "pwd 12 15" \
		"now_playing 8 6" \
		# "cpu 240 136" \
		"storage 0 14" \
		"load 8 15" \
		# "tmux_mem_cpu_load 234 136" \
		"weather 4 15" \
		"battery 1 15" \
		# "rainbarf 0 0" \
		"xkb_layout 6 15" \
		# "sound_volume 2 15" \
		"currency 5 15"
		"date_day 10 15" \
		"date 10 15 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"time 10 15 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		# "utc_time 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
	)
fi
